name: Publish Python Package to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - cocotb/pyproject.toml # Trigger the workflow only if the VERSION file changes

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Read version number
        id: read_version
        run: |
          echo "version=$(python3 cocotb/caravel_cocotb/__version__.py)" >> $GITHUB_ENV

      - name: Build package
        run: |
          cd cocotb
          make dist

      - name: Publish
        if: ${{ env.NEW_TAG != 'NO_NEW_TAG' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: cocotb/dist
